name: Deploy Web

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-web
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - run: node -v

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: pnpm -v

      - run: pnpm install --frozen-lockfile

      - run: pnpm check-types

      - run: pnpm lint

      - run: pnpm --filter web build

      - run: pnpm dlx vercel deploy --prod --yes --cwd apps/web --token=${{ secrets.VERCEL_TOKEN_WEB_FRAMEFORGE }}