name: Deploy Web
on:
    push:
        branches:
            - main
concurrency:
    group: deploy-web
    cancel-in-progress: true
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.22.3"
            - name: Verify Node
              run: node -v
            - name: Install pnpm
              run: npm install -g pnpm@11.0.0
            - name: Verify pnpm
              run: pnpm -v
            - name: Install dependencies
              run: pnpm install
            - name: Type check
              run: pnpm check-types
            - name: Lint
              run: pnpm lint
            - name: Build
              run: pnpm --filter web build
            - name: Deploy
              run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN_WEB_FRAMEFORGE }}
