name: Deploy Web

on:
    push:
        branches:
            - main

concurrency:
    group: deploy-web
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 11.0.0

            - name: Verify Node
              run: node -v

            - name: Verify pnpm
              run: pnpm -v

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Type check
              run: pnpm check-types

            - name: Lint
              run: pnpm lint

            - name: Build
              run: pnpm --filter web build

            - name: Deploy to Vercel
              run: pnpm dlx vercel deploy --prod --yes --cwd apps/web --token=${{ secrets.VERCEL_TOKEN_WEB_FRAMEFORGE }}
